# Generated by Django 3.1 on 2021-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210313_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('1', 'India')], default='India', max_length=10),
        ),
    ]
