# Generated by Django 3.1 on 2021-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210313_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(default=9999999988, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('1', 'India')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
